name: url_strategy
description: >-2
  Flutter package that allows setting the web app URL strategy with a single line of code.
version: 0.1.1
homepage: https://github.com/simpleclub/url_strategy/tree/main/url_strategy

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
